import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import dynamic from "next/dynamic";
import Providers from "@/store/Provider";

const inter = Inter({ subsets: ["latin"] });
// const NoSSR = dynamic(() => import("@/components/Header"), { ssr: false });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} flex flex-col`}>
        <Providers>
          <div>
            <Header />
          </div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
